-- Up
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    sub VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- Down
DROP TABLE IF EXISTS users;
